### ISSUE TITLE
Calendar UI

### ISSUE THREAD

**Issue by richardsun29** [ucladevx/Bmaps-Frontend#218]
Mock:
![image](https://user-images.githubusercontent.com/17267100/48231438-f74b2f80-e362-11e8-8eaa-e5ff1886b7f5.png)

- [x] Display calendar
- [x] Switch between map and calendar
- [ ] Show dot on days with events
- [ ] List events on the currently selected day
- [ ] Search

**Comment by TrinaKat** [comment]
As of #263:
TODO:

- Event descriptions within each calendar cell include all events with that day number rather than all events in current month and year with that day number.
- The sidebar grows too wide when there's a long name with no spaces (fix via css, unrelated to calendar)
- Filter UI in sidebar does not filter calendar event data (need to write filtering functions in event.service.ts
- BUG: event descriptions in calendar cells only show on reload
